package com.sv;
import java_cup.runtime.*;

class Parser;

// simples
terminal PAREN_O, PAREN_I;
terminal COMA, DOT_COMA, DOT;
terminal ALL, ASSIGN, MAYOR, MENOR, MAYOR_IGUAL, MENOR_IGUAL, NOT_EQUAL;
// datos primitivos
terminal INT, DECI, STR;
terminal VAR;
//joins
terminal INNER_JOIN, LEFT_JOIN, RIGHT_JOIN, FULL_JOIN, JOIN;
// reservadas
terminal CREATE, TABLE, SELECT, FROM, WHERE, UPDATE, SET, DISTINCT, COUNT;
terminal INSERT, INTO, VALUES, ON, AS;
// data types numericos
terminal DT_INT, DT_DECIMAL, DT_FLOAT, DT_NUMERIC;
// data types de texto
terminal DT_CHAR, DT_VARCHAR, DT_TEXT;
// data types de fecha y hora
terminal DT_DATE, DT_TIME, DT_DATETIME;
// data types booleanos
terminal DT_BOOLEAN;

terminal ERROR;

//simbolos no terminales
non terminal Object sql;
non terminal Object sentence;
non terminal Object create_stmt;
non terminal Object select_stmt;
non terminal Object update_stmt;
non terminal Object insert_stmt;
non terminal Object insert_into;
non terminal Object insert_complement;
non terminal Object assign_condition_list;
non terminal Object distinct_stmt;
non terminal Object count_stmt;
//
non terminal Object create_elements;
non terminal Object elements;
non terminal Object condition;
non terminal Object comparator;
non terminal Object primitives;
non terminal Object variable;
non terminal Object var_alias;
non terminal Object opt_alias;
non terminal Object column_list;
non terminal Object column_data;
non terminal Object primitive_list;
non terminal Object join_expr;
non terminal Object join_stmt;
non terminal Object from_expr;
non terminal Object where_expr;
non terminal Object data_type;

precedence left ASSIGN;
precedence left MAYOR, MENOR, MAYOR_IGUAL, MENOR_IGUAL, NOT_EQUAL;

start with sql;
//estructura general de una consulta SQL
sql ::=
    sentence DOT_COMA
    | sql sentence DOT_COMA
    ;

sentence ::= create_stmt
    | select_stmt
    | update_stmt
    | insert_stmt
    ;
// CREATE TABLE NOMBRE_TABLA ( LISTA_COLUMNAS )
create_stmt ::=
    CREATE TABLE VAR PAREN_O create_elements PAREN_I
    ;

create_elements ::=
    column_data
    | create_elements COMA column_data
    | ALL
    ;

column_data ::=
    VAR data_type
    ;

data_type ::=
    DT_INT
    | DT_DECIMAL PAREN_O INT COMA INT PAREN_I
    | DT_FLOAT
    | DT_NUMERIC PAREN_O INT COMA INT PAREN_I
    | DT_CHAR PAREN_O INT PAREN_I
    | DT_VARCHAR PAREN_O INT PAREN_I
    | DT_TEXT
    | DT_DATE
    | DT_TIME
    | DT_DATETIME
    | DT_BOOLEAN
    ;
/*
// SELECT LISTA_COLUMNAS FROM NOMBRE_TABLA
select_stmt ::=
    SELECT elements from_expr
    | SELECT distinct_stmt from_expr
    | SELECT COUNT PAREN_O count_stmt PAREN_I from_expr
    ;

elements ::=
    column_list
    | ALL
    ;

column_list ::=
    variable
    | column_list COMA variable
    ;
variable ::=
    VAR
    | VAR DOT VAR
    ;

distinct_stmt ::=
    DISTINCT elements
    ;

count_stmt ::=
    distinct_stmt
    | ALL
    | variable
    ;

where_expr ::= 
     WHERE condition
    ;
from_expr ::=
    FROM var_alias
    | FROM var_alias where_expr
    | FROM var_alias join_expr
    ;

join_expr ::=
    join_stmt var_alias ON condition
    | join_expr join_stmt var_alias ON condition
    ;

join_stmt ::=
    INNER_JOIN
    | LEFT_JOIN
    | RIGHT_JOIN
    | FULL_JOIN
    | JOIN
    ;

var_alias ::=
    VAR opt_alias
    ;
opt_alias ::= */
/* vacío *//*

    | AS VAR
    | VAR
    ;

condition ::=
    variable comparator primitives
    variable comparator variable
    ;

comparator ::=
    ASSIGN
    | MAYOR
    | MENOR
    | MAYOR_IGUAL
    | MENOR_IGUAL
    | NOT_EQUAL
    ;

primitives ::=
    VAR
    | INT
    | DECI
    | STR
    ;

// UPDATE NOMBRE_TABLA SET VAR = PRIMITIVO WHERE CONDITION
update_stmt ::=
    UPDATE VAR SET assign_condition_list WHERE condition
    ;

assign_condition_list ::=
    VAR ASSIGN primitives
    | assign_condition_list COMA VAR ASSIGN primitives
    ;

// INSERT STATEMENT aqui pueden ir ambos insert o uno de ellos
insert_stmt ::=
    insert_into insert_complement
    ;

// INSERT INTO NOMBRE_TABLA (LISTA_COLUMNAS) VALUES (LISTA_VALORES)
insert_into ::=
    INSERT INTO VAR PAREN_O column_list PAREN_I
    | INSERT INTO VAR
    ;

insert_complement ::=
    VALUES PAREN_O primitive_list PAREN_I
    | select_stmt
    ;
primitive_list ::=
    primitives
    | primitive_list COMA primitives
    ;*/
